### ISSUE TITLE
Wont work, token not accepted?

### ISSUE THREAD

**Issue by HansDrost** [FoglyOgly/Meowth#5] opened 2017-08-08 13:47 UTC
I did everything you wrote and it didn't work. A bit of searching on internet tells me that python wont work with the bot token? Tried the "self bot" option, didn't work with that token either.

**Comment by FoglyOgly** [comment] 2017-08-08 18:29
How did it not work? It didn't connect to Discord at all? Make sure you're using the bot token, not the client id

**Comment by HansDrost** [comment] 2017-08-08 20:37
My apologies, i apparently broke the code with the image ID stuff. Weird that the error was directed at the token (dont have the error message anymore..) It is working now, just not the team part (can keep on assigning to team, even if you are all ready in one). Nice bot though!

**Comment by FoglyOgly** [comment] 2017-08-08 21:22
Thanks. Is there any traceback when the !team error you describe happens?

**Comment by 6-lasers** [comment] 2017-08-08 23:33
Hans, did you configure the team role IDs (step 2 of Configure Meowth in the README)? In my experience, the "can keep on assigning to team" bug is caused by the IDs not being set up properly.

I also have a commit pending integration which removes the need for manually configuring the role IDs.

**Comment by HansDrost** [comment] 2017-08-09 07:31
Yes, the roles are the same as the discord roles. Just to be sure I copy pasted them. Still able to join multiple roles.

**Comment by FoglyOgly** [comment] 2017-08-09 13:56
I was able to reproduce the error. Assuming you're working with the latest meowth.py file in the master branch, in line 1018, change
`if r.id in roles:`
to
`if r.mention in roles:`

Let me know if this works.

**Closed** 2017-08-11 16:52 UTC
