### ISSUE TITLE
Python code outdated?

### ISSUE THREAD

**Issue by altnine** [FoglyOgly/Meowth#14] opened 2017-08-10 16:09 UTC
Hello. Thank you for the great bot set up, but my developer is having trouble implementing them. The command !otw is erroring out. He thinks the discord.py is possibly outdated? Any support would greatly be appreciated! Thanks again!

**Comment by 6-lasers** [comment] 2017-08-10 18:45
Is there an error message? Does Meowth send anything in chat? Does Meowth print any kind of error in the console window?

If you can supply this information, I'll see if I'm able to reproduce the errors.

**Comment by altnine** [comment] 2017-08-12 23:49
Sorry getting back to you late. Discord has been very busy and life and whatnot lol. 

He says the exceptions are related to the discord.py. I sent him you comment word for word and that was his reply. He linked me a pic of the command prompt but I don't know how to get the pic to you.

**Comment by FoglyOgly** [comment] 2017-08-17 17:17
Could just post the link to the picture here if you want.

**Comment by 6-lasers** [comment] 2017-08-17 21:04
Yeah, you can post a link or you can just drag-and-drop or copy/paste an image onto the comment box and it'll get uploaded.

**Comment by FoglyOgly** [comment] 2017-08-20 15:12
I'm closing this issue because there isn't a problem with discord.py or anything being outdated. You can post a picture of whatever error you're having in a new issue if you get around to it.

**Closed by FoglyOgly** 2017-08-20 15:12 UTC
